// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2HdWF5vErOpnWjN8qGjaezi78llzYeJA',
    appId: '1:802347285834:web:c702ef26f6effdc5d655b3',
    messagingSenderId: '802347285834',
    projectId: 'tugas-todo-fcm',
    authDomain: 'tugas-todo-fcm.firebaseapp.com',
    storageBucket: 'tugas-todo-fcm.firebasestorage.app',
    measurementId: 'G-H04V3263KE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoJGT98Klb_xLUafiWmyxCP5wC7zwT1RQ',
    appId: '1:802347285834:android:9cd921cb8e8e14e5d655b3',
    messagingSenderId: '802347285834',
    projectId: 'tugas-todo-fcm',
    storageBucket: 'tugas-todo-fcm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnvRZacELu3fCz06rA2WdS2rIy2k86lPo',
    appId: '1:802347285834:ios:bbab12729604e867d655b3',
    messagingSenderId: '802347285834',
    projectId: 'tugas-todo-fcm',
    storageBucket: 'tugas-todo-fcm.firebasestorage.app',
    iosBundleId: 'com.example.tugasFcmProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnvRZacELu3fCz06rA2WdS2rIy2k86lPo',
    appId: '1:802347285834:ios:bbab12729604e867d655b3',
    messagingSenderId: '802347285834',
    projectId: 'tugas-todo-fcm',
    storageBucket: 'tugas-todo-fcm.firebasestorage.app',
    iosBundleId: 'com.example.tugasFcmProvider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2HdWF5vErOpnWjN8qGjaezi78llzYeJA',
    appId: '1:802347285834:web:4effe4f8757536b4d655b3',
    messagingSenderId: '802347285834',
    projectId: 'tugas-todo-fcm',
    authDomain: 'tugas-todo-fcm.firebaseapp.com',
    storageBucket: 'tugas-todo-fcm.firebasestorage.app',
    measurementId: 'G-0MHQ6ZJML8',
  );
}
